# Generated by vmake version 10.7d

# Define path to each library
LIB_STD = /opt/lintula/modelsim/10.7d/modeltech/linux_x86_64/../std
LIB_IEEE = /opt/lintula/modelsim/10.7d/modeltech/linux_x86_64/../ieee
LIB_WORK = my_lib
LIB_MY_LIB = my_lib

# Define path to each design unit
IEEE__std_logic_1164 = $(LIB_IEEE)/_lib.qdb
STD__textio = $(LIB_STD)/_lib.qdb
IEEE__numeric_std = $(LIB_IEEE)/_lib.qdb
MY_LIB__tb_lock__testbench = $(LIB_MY_LIB)/_lib.qdb
MY_LIB__tb_lock = $(LIB_MY_LIB)/_lib.qdb
MY_LIB__lock_pkg = $(LIB_MY_LIB)/_lib.qdb
MY_LIB__lock__rtl = $(LIB_MY_LIB)/_lib.qdb
MY_LIB__lock = $(LIB_MY_LIB)/_lib.qdb
VCOM = vcom
VLOG = vlog
VOPT = vopt
SCCOM = sccom

whole_library : $(LIB_MY_LIB)/_lib.qdb

$(LIB_MY_LIB)/_lib.qdb : vhd/lock.vhd \
		$(MY_LIB__lock_pkg) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) vhd/lock_pkg.vhd tb/tb_lock.vhd \
		$(MY_LIB__lock_pkg) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164)
	$(VCOM) -2002 -work my_lib  vhd/lock.vhd
	$(VCOM) -2002 -work my_lib -check_synthesis \
		 vhd/lock_pkg.vhd
	$(VCOM) -2002 -work my_lib  tb/tb_lock.vhd

